#!/bin/sh

YEAR=""
DAY=""

while [[ $# -gt 0 ]]; do
  case $1 in
  -y | --year)
    YEAR="$2"
    shift 2
    ;;
  -d | --day)
    DAY="$2"
    shift 2
    ;;
  *)
    echo "Unknown option $1"
    exit 1
    ;;
  esac
done

if [[ -z "$YEAR" || -z "$DAY" ]]; then
  echo "Usage: $0 -y <YEAR> -d <DAY>"
  exit 1
fi

if [[ "$YEAR" -eq 2024 ]]; then
  javac "$YEAR/utils/FileUtils.java" "$YEAR/Day$DAY/"*.java -d out
  if [[ $? -ne 0 ]]; then
    echo "Compilation failed."
    exit 1
  fi
  java -cp out "Day$DAY.Main"
elif [[ "$YEAR" -eq 2025 ]]; then
  node "2025/Day$DAY/main.js"
else
  echo "Unsupported year: $YEAR"
  exit 1
fi

